services:

  nginx:
    image: nginx:1.27
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - dept_viewer

  db:
    image: postgres:16.4
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: dept_viewer
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev -d dept_viewer" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"


  dept_viewer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dept_viewer
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static:/app/static/
      - media:/app/media/
    depends_on:
      db:
        condition: service_healthy
    entrypoint: >
      sh -c "python manage.py makemigrations &&
                 python manage.py migrate &&
                 python manage.py collectstatic --noinput &&
                 python manage.py generate_data & 
                 exec gunicorn dept_viewer.wsgi:application -b 0.0.0.0:8000"

  redis:
    image: redis:7.4
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pg_data:
  static:
  media: