# Generated by Django 4.2.16 on 2024-11-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
